---
- name: Remove all generated VMs
  hosts: localhost

  vars_files:
    - ~/.ansible/variables/proxmox_info.yml
    - ~/.ansible/variables/rsa_key.yml
    - ~/.ansible/variables/multi-container.yml

  tasks:
  - name: remove VM 
    community.proxmox.proxmox:
      node: "{{ proxmox_node }}"
      api_user: "{{ proxmox_api_user }}"
      api_host: "{{ proxmox_api_host }}"
      api_token_id: "{{ proxmox_api_token_id }}"
      api_token_secret: "{{ proxmox_api_token_secret }}"
      vmid: "{{ item.vmid }}"
      state: absent

    loop: "{{ containers }}"
  - name: Delete VM_inventory file
    ansible.builtin.file:
      path: ~/.ansible/inventories/vm_inventory.yml
      state: absent
