spring.application.name=learning_platform

# Savienojums ar PostgreSQL datubāzi
spring.datasource.url=jdbc:postgresql://${DATABASE_URL}/testeris
spring.datasource.username=${DATABASE_USER}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

#Nomainīt beigās, lai saglabātu datus 
spring.jpa.hibernate.ddl-auto=create

spring.jpa.show-sql=true

# TESTING LOGS
logging.level.root=INFO
logging.level.lv.slugboot.app=DEBUG

logging.level.org.springframework.web=TRACE
logging.level.org.springframework.websocket=TRACE

logging.level.org.springframework.transaction=DEBUG